// CREAR CARPETA CONTEXTS EN SRC
// CREAR NOMBRE ARHIVO CON EL NOMBRE DE LO QUE VAMOS A HACER + CONTEXT ej. counterContext.js
// CREAR UN ARCHIVO:  export const CounterContext = createContext(); (CON EL NOMBRE EN MAYUSCULA);

// CREAR UNA NUEVA CARPETA PROVIDERS EN SRC
// CREAR ARCHIVO ej. CounterProvider.jsx
// NOS TRAEMOS LOS DATOS QUE NECESITEMOS AL PROVIDER COMO POR ej. el STATE etc
// CREAMOS Y RETORNAMOS UNA ETIQUETA CON EL NOMBRE DEL CONTEXT
// EL PROVIDER SIEMPRE RECIBE {CHILDREN} Y LO PASA A LA ETIQUETA
// LA ETIQUETA DEL CONTEXT TIENE UN METODO LLAMADO .PROVIDER Y LUEGO TENEMOS QUE PONERLE EL VALUE = {{param, param}} (SIEMPRE ES UN OBJETO LO QUE PASAMOS Y AHI INCLUIMOS TODOS LOS PARAMETROS QUE QUERAMOS PASARLE)
